// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiDemo2_WebApi.Data;

namespace RestApiDemo2_WebApi.Migrations
{
    [DbContext(typeof(BaseItemContext))]
    [Migration("20210106101933_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("RestApiDemo_WebApi.Models.Cookware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cookwares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Plate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fork"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spoon"
                        });
                });

            modelBuilder.Entity("RestApiDemo_WebApi.Models.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fruits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pear"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Orange"
                        });
                });

            modelBuilder.Entity("RestApiDemo_WebApi.Models.Vegetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vegetables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Onion"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
